name: gpu_env
channels:
- pytorch
- dglteam
- conda-forge
- fragcolor
- anaconda
- defaults
dependencies:
- cudatoolkit=11.3
- cudnn=7.6.5
- python=3.7.4
- python-dateutil=2.8.0
- pip=19.2.3
- pytorch
- torchvision
- pillow==6.1
- dgl-cuda11.3
- numpy
- matplotlib
- tensorboard=1.14.0
- tensorboardx=1.8
- future=0.18.2
- absl-py
- networkx=2.3
- scikit-learn
- scipy=1.3.0
- h5py=2.9.0
- mkl=2019.4
- ipykernel=5.1.2
- ipython=7.7.0
- ipython_genutils=0.2.0
- ipywidgets=7.5.1
- plotly=4.1.1
- scikit-image=0.15.0
- requests==2.22.0
- tqdm==4.43.0
- pip:
  - tensorflow-gpu==2.1.0
  - tensorflow-estimator==2.1.0
  - tensorboard==2.1.1
  - ogb==1.2.2